/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingest/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listActiveRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMachines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Event: {
            /** Format: uuid */
            id: string;
            session_id: string;
            /** Format: uuid */
            run_id?: string;
            /** Format: int64 */
            sequence: number;
            /** Format: date-time */
            occurred_at: string;
            kind: string;
            source: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        IngestRequest: {
            /** Format: uuid */
            machine_id: string;
            events: components["schemas"]["Event"][];
        };
        IngestResponse: {
            accepted: number;
            duplicates: number;
            rejected: {
                id?: string;
                reason?: string;
            }[];
        };
        Run: {
            /** Format: uuid */
            id: string;
            session_id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: date-time */
            last_activity_at: string;
            status: string;
            model?: string;
            reasoning_effort?: string;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            cached_input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            reasoning_tokens: number;
            close_reason?: string;
        };
        Summary: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            agent_seconds: number;
            wall_clock_seconds: number;
            project_span_seconds: {
                [key: string]: number;
            };
            parallelism_peak: number;
            parallelism_average: number;
            run_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cached_input_tokens: number;
            /** Format: int64 */
            reasoning_tokens: number;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int64 */
            run_count: number;
            agent_seconds: number;
            /** Format: date-time */
            last_active_at?: string | null;
        };
        Session: {
            id: string;
            /** Format: uuid */
            machine_id: string;
            /** Format: uuid */
            project_id: string;
            source: string;
            codex_version?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: date-time */
            last_activity_at: string;
            /** Format: int64 */
            run_count: number;
        };
        Machine: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at?: string | null;
        };
    };
    responses: never;
    parameters: {
        From: string;
        To: string;
        ProjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerMachine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    machine_id?: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Registered machine */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        machine_id: string;
                        token: string;
                    };
                };
            };
        };
    };
    ingestEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Batch result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: {
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
                project_id?: components["parameters"]["ProjectId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calculated summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
        };
    };
    getTimeline: {
        parameters: {
            query?: {
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
                project_id?: components["parameters"]["ProjectId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        from: string;
                        /** Format: date-time */
                        to: string;
                        runs: components["schemas"]["Run"][];
                    };
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: components["schemas"]["Project"][];
                    };
                };
            };
        };
    };
    listActiveRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["Run"][];
                    };
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["Session"][];
                    };
                };
            };
        };
    };
    listMachines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Machine list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        machines: components["schemas"]["Machine"][];
                    };
                };
            };
        };
    };
}
